spring:
  application:
    name: jara3-routing-service
server:
  port: 8762
eureka:
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-0.eureka:8761/eureka}
      register-with-eureka: true
  instance:
    preferIpAddress: true