spring:
  datasource:
    platform: H2
    url: jdbc:h2:mem:jara3-local-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true

eureka:
  client:
    enabled: false