spring:
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none #update # TODO data.sql seed with admin admin...
    defer-datasource-initialization: true
  datasource:
    platform: mySQL
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/jara3_db
    username: jara3-dev
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver