spring:
  application:
    name: jara3-user-service

server:
  port: 8772

eureka:
  client:
    enabled: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-0.eureka:8761/eureka}
      register-with-eureka: true
  instance:
    preferIpAddress: true

url:
  login: "/api/login"
  admin: "/api/admin"

jwt:
  secret: "secret"
  token:
    expiration-in-minutes:
      access: 15
      refresh: 1440

response:
  authenticate:
    success: "Authentication Successful"
    fail:
      no-user-exists: "Authentication Failed: user '%s' does not exist"
      incorrect-password: "Authentication Failed: password doesn't match"
      invalid-credentials: "Authentication Failed: "
  register:
    success: "Registration Successful"
    fail:
      invalid-credentials: "Registration Failed: "
      user-exists: "Registration Failed: username '%s' already exists"