spring:
  application:
    name: jara3-user-service

server:
  port: 8772

eureka:
  client:
    enabled: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-0.eureka:8761/eureka}
      register-with-eureka: true
  instance:
    preferIpAddress: true

response:
  authenticate:
    success: "Authentication Successful"
    fail:
      no-user-exists: "Authentication Failed: user '%s' does not exist"
      incorrect-password: "Authentication Failed: password doesn't match"