spring:
  application:
    name: jara3-user-service
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    platform: H2
    url: jdbc:h2:mem:jara3-local-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
server:
  port: 8772
eureka:
  client:
    enabled: false
response:
  register:
    success: "Registration Successful"
    fail:
        invalid-credentials: "Registration Failed: "
        user-exists: "Registration Failed: username '%s' already exists"
  authenticate:
    success: "Authentication Successful"
    fail:
      invalid-credentials: "Authentication Failed: "
      no-user-exists: "Authentication Failed: user '%s' does not exist"
      incorrect-password: "Authentication Failed: password doesn't match"


# This version is used when testing (mvn clean test)
# Also as a base for the other application-*.yaml files, so no need to duplicate properties