spring:
  application:
    name: jara3-user-service
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  datasource:
    platform: mySQL
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/jara3_db
    username: jara3-dev
    password: password
server:
  port: 8772
eureka:
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-0.eureka:8761/eureka}
      register-with-eureka: true
  instance:
    preferIpAddress: true